customer/app/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required
from sqlalchemy import func

from .extentions import db
from .models import Customer, Shop, ProductOrder, CustomerPrice, Product


cs = Blueprint('cs', __name__)


@cs.route('/')
@login_required
def index():
    customer_id = current_user.customer_id
    shop_id = current_user.shop_id

    if customer_id == 15615:
        page = request.args.get('page', 1, type=int)
        customer = Customer.query.get(customer_id)

        orders = ProductOrder.query.filter_by(customer_id=customer_id).order_by(ProductOrder.id.desc()).paginate(page=page, per_page=20)

        return render_template('orfeu.html', customer=customer, orders=orders, page=page)

    else:

        shop = Shop.query.get_or_404((customer_id, shop_id))
        orders = ProductOrder.query.filter_by(customer_id=customer_id).filter_by(shop_id=shop_id).order_by(ProductOrder.id.desc()).all()

        items = CustomerPrice.query.filter_by(customer_id=customer_id).all()

        return render_template('index.html', shop=shop, orders=orders, items=items)


@cs.route('/order', methods=['POST'])
@login_required
def order():

    customer_id = current_user.customer_id
    shop_id = current_user.shop_id
    customer = Customer.query.get(customer_id)

    order = ProductOrder()
    order.sales_by = customer.staff
    order.customer_id = customer_id
    order.shop_id = shop_id
    product = request.form['item']

    order.item = product

    # get the contract price for the item of the customer
    item_price = CustomerPrice.query.filter(CustomerPrice.customer_id == customer_id, CustomerPrice.product_id == product).first()
    price = item_price.price

    order.price = price
    order.qty = request.form['qty']

    db.session.add(order)
    db.session.commit()
        
    flash('商品を発注しました。', 'success')

    return redirect(url_for('cs.index'))


@cs.route('/order/<int:id>')
@login_required
def order_detail(id):
    order = ProductOrder.query.get(id)

    return render_template('order-detail.html', order=order)


# delete order
@cs.route('/delete/<int:id>')
@login_required
def order_delete(id):
    order = ProductOrder.query.get(id)
    db.session.delete(order)
    db.session.commit()

    flash('注文を削除しました。', 'warning')

    return redirect(url_for('cs.index'))


@cs.route('/stats')
@login_required
def stats():
    customer_id = current_user.customer_id

    customer = Customer.query.get(customer_id)

    parent_id = customer.parent_id

    customers = Customer.query.filter(Customer.parent_id == parent_id).all()

    page = request.args.get('page', 1, type=int)

    date_from = request.args.get('date_from')
    date_to = request.args.get('date_to')

    # sum_qty_month = db.session.query(func.sum(ProductOrder.qty)).filter(ProductOrder.sales_by ==current_user.id)\
    #     .filter(extract('year', ProductOrder.date) == this_year).filter(extract('month', ProductOrder.date) == this_month)\
    #     .filter(ProductOrder.item != 901).scalar()

    if parent_id:
        if date_from and date_to:
            orders = ProductOrder.query.filter(ProductOrder.customer_id.in_([c.id for c in customers]))\
                .filter(func.DATE(ProductOrder.date) <= date_to).filter(func.DATE(ProductOrder.date) >= date_from)\
                    .order_by(ProductOrder.id.desc()).paginate(page=page, per_page=30)

            co2 = db.session.query(func.sum(Product.co2 * ProductOrder.qty /1000))\
                .filter(ProductOrder.customer_id.in_([c.id for c in customers]))\
                    .filter(func.DATE(ProductOrder.date) <= date_to).filter(func.DATE(ProductOrder.date) >= date_from)\
                        .scalar()
            pcr = db.session.query(func.sum(Product.pcr * ProductOrder.qty /1000))\
                .filter(ProductOrder.customer_id.in_([c.id for c in customers]))\
                    .filter(func.DATE(ProductOrder.date) <= date_to).filter(func.DATE(ProductOrder.date) >= date_from)\
                        .scalar()
    
            return render_template('stats.html', orders=orders, date_from=date_from, date_to=date_to, parent_id=parent_id, co2=co2, pcr=pcr)

        else:
            orders = ProductOrder.query.filter(ProductOrder.customer_id.in_([c.id for c in customers])).order_by(ProductOrder.id.desc()).paginate(page=page, per_page=30)

            return render_template('stats.html', orders=orders, date_from=date_from, date_to=date_to, parent_id=parent_id)


    else:
        customer_filter = ProductOrder.query.filter(ProductOrder.customer_id == customer_id)

        if date_from and date_to:
            dates_filter = customer_filter.filter(func.DATE(ProductOrder.date) <= date_to).filter(func.DATE(ProductOrder.date) >= date_from)

            orders = dates_filter.order_by(ProductOrder.id.desc()).paginate(page=page, per_page=30)

            co2 = db.session.query(func.sum(ProductOrder.price * ProductOrder.qty /1000))\
                .filter(ProductOrder.customer_id == customer_id)\
                    .filter(func.DATE(ProductOrder.date) <= date_to).filter(func.DATE(ProductOrder.date) >= date_from)\
                        .scalar()

            # pcr = ProductOrder.query.filter(ProductOrder.customer_id == customer_id)\
            #     .filter(func.DATE(ProductOrder.date) <= date_to).filter(func.DATE(ProductOrder.date) >= date_from)\
            #         .func.sum(ProductOrder.price * ProductOrder.qty).scalar()


            pcr = db.session.query(func.sum(ProductOrder.qty * Product.co2))\
                .filter(ProductOrder.customer_id == customer_id)\
                    .filter(func.DATE(ProductOrder.date) <= date_to).filter(func.DATE(ProductOrder.date) >= date_from)\
                        .scalar()

            return render_template('stats.html', orders=orders, date_from=date_from, date_to=date_to, parent_id=parent_id, co2=co2, pcr=pcr)

        else:
            orders = customer_filter.order_by(ProductOrder.id.desc()).paginate(page=page, per_page=30)

            return render_template('stats.html', orders=orders, date_from=date_from, date_to=date_to, parent_id=parent_id)

customer/app/templates/_macros.html
{##### log-in form #####}

{% macro render_login_field_label(field, label_text) %}
  {{ field.label(class_="block text-gray-700 text-sm mb-2 ml-3", text=label_text) }}
{% endmacro %}

{% macro render_login_field(field) %}
  {{ field(**kwargs)|safe }}
{% endmacro %}

{% macro render_login_form_error() %}
{% for field in varargs %}
{% if field.errors %}
{% for error in field.errors %}
<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" x-data="{ show: true }" x-show="show" x-init="setTimeout(() => show = false, 3000)">
  <p class="text-center"><span class="block sm:inline">{{ error }}</span></p>
</div>
{% endfor %}
{% endif %}
{% endfor %}
{% endmacro %}

{##### log-in form #####}

customer/app/templates/index.html
{% extends "layout.html" %}
{% block content %}
{% include "navbar.html" %}
{% include "_flashing.html" -%}

<div class="container md:max-w-md mx-auto">

    <div class="mt-8 flex justify-between px-3" x-data="getToday">
        <h1 class="font-bold text-xl text-gray-500">事業所情報</h1>
        <p class="text-sm text-gray-500 self-end" x-text="today"></p>
    </div>

    <div class="mx-auto p-6 bg-white shadow-lg rounded-lg mt-3 mb-5">
        <p class="text-gray-500 text-right">{{ shop.customer_id }} - {{ shop.id }}</p>
        <p class="mt-2 text-gray-600">{{ shop.customer.name }}</p>
        <h2 class="mt-2 text-gray-800 text-2xl">{{ shop.name }}</h2>
        <p class="mt-2 text-gray-600">{{ shop.department }}</p>
        <p class="mt-2 text-gray-600">{{ '〒{}-{}'.format(shop.zip[:3], shop.zip[3:]) }} {{ shop.prefecture }} {{ shop.city }}
            {{ shop.town }} {{ shop.address }} {{ shop.building }}</p>
        <p class="mt-2 text-gray-600">{{ shop.telephone }}</p>
    </div>

    <div class="flex justify-between mt-8 px-3">
        <h1 class="font-bold text-xl text-gray-500">注文入力</h1>
    </div>

    <form action="/order" method="POST" x-data="{ item: '', qty: '', open: false }">

    <div class="my-3 pt-5 px-8 bg-white shadow-lg rounded-lg">

        <div class="mt-3">
            <label for="item" class="mr-3 text-gray-500 text-sm">商品</label>
            <select x-model="item" name="item" class="border-b text-gray-800 text-lg"  required>
                <option value="" disabled selected>-- 商品 --</option>
                {% for item in items %}
                <option value="{{ item.product_id }}">{{ item.product.abbre }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="mt-5">
            <label for="qty" class="mr-3 text-gray-500 text-sm">数量</label>
            <select x-bind:disabled="!item.length" x-model="qty" name="qty" class="border-b text-gray-800 text-lg" required>
                <option value="" disabled>-- 箱数 --</option>
                <option value="1">1 箱</option>
                <option value="2">2 箱</option>
                <option value="3">3 箱</option>
                <option value="4">4 箱</option>
                <option value="5">5 箱</option>
            </select>
        </div>

        <!-- confirmation button -->
        <div class="flex justify-center">
            <button x-bind:disabled="!qty.length" x-on:click="open = true" type="button" class="my-5 mx-7 bg-blue-500 shadow-xl hover:bg-blue-800 text-sm text-white py-1 px-10 rounded-full">内容確認</button>
        </div>
    </div>

    <!-- order confirm modal goes here -->
    <div x-show="open" class="fixed inset-0 bg-black bg-opacity-70 flex justify-center items-center">
        <div class="bg-white mx-3 md:mx-0 border p-6 shadow-md">
            <h2 class="font-bold text-sm">発注内容の確認</h2>
            <p class="text-gray-500 text-sm mt-5">以下の商品と数量でよろしいですか？</p>
            <p class="my-3 text-gray-500 text-sm">
                <!-- <span class="text-gray-800 text-lg" x-text="$refs.item.options[$refs.item.selectedIndex].text"></span> を  -->
                <span class="text-gray-800 text-lg" id="mItem"></span> を 
                <span class="text-gray-800 text-lg" x-text="qty"></span> 箱</p>
            <p class="font-bold mt-5 text-right">
                <span @click="open = false" class="px-3 py-1 rounded-md text-gray-500 cursor-pointer hover:bg-gray-100">中止</span>
                <button type="submit" class="font-bold px-3 rounded-md cursor-pointer text-blue-500 hover:bg-blue-100">発注</button>
            </p>
        </div>
    </div>

    </form>

    <div class="mt-8" x-data="{ open: false }">
        <h1 class="font-bold text-xl text-gray-500 px-3">発注履歴</h1>

        {% if orders %}
        <table class="w-full my-5 text-sm">
            <thead>
                <tr class="border-black border-b">
                    <th class="p-1">日付</th>
                    <th class="p-1">番号</th>
                    <th class="p-1">商品</th>
                    <th class="p-1">単価</th>
                    <th class="p-1">数量</th>
                    <th class="p-1"></th>
                </tr>
            </thead>
            <tbody>
            {% for order in orders %}
                <tr class="border-b">
                    <td class="p-1">{{ order.date.strftime('%m-%d') }}</td>
                    <td class="p-1">{{ '{:06d}'.format(order.id) }}</td>
                    <td class="p-1">{{ order.product.name }}</td>
                    <td class="p-1">{{ order.price }}</td>
                    <td class="p-1 text-center">{{ order.qty }}</td>
                    <td class="">
                    {% if order.delivery_check is none %}
                    <a href="/delete/{{ order.id }}" onclick="confirm('この注文を削除してよろしいですか？');">
                        <svg xmlns="http://www.w3.org/2000/svg" class="p-1 h-6 w-6 rounded-full hover:bg-red-200 hover:text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                        </svg>
                    </a>
                    {% else %}
                    {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    
    {% else %}
    <p class="my-5 mx-2">...なし</p>
    {% endif %}

                                        <!-- delete confirm modal goes here -->
                                        <!-- <div x-show="open" class="fixed inset-0 bg-black bg-opacity-10 flex justify-center items-center">
                                            <div class="bg-white mx-3 md:mx-0 border p-6 shadow-md">
                                                <h2 class="font-bold text-sm">発注内容の確認</h2>
                                                <p class="text-gray-500 text-sm mt-5">この注文を削除しますか？</p>
                                    
                                                <div class="flex font-bold mt-8 text-sm justify-end">
                                                    <p x-on:click="open = false" class="px-3 py-1 rounded-md text-gray-500 cursor-pointer hover:bg-gray-100">中止</p>
                                                    <a  class="ml-8 px-3 py-1 rounded-md text-red-500 hover:bg-red-100" @click="open = false">削除</a>
                                                </div>
                                            </div>
                                        </div> -->
    </div>
</div>

<!-- alpine.js -->
<script>
    const getToday = () => {
        let now = new Date();
        let year = now.getFullYear();
        let month = now.getMonth() + 1;
        let date = now.getDate();
        let hours = now.getHours().toString().padStart(2, '0');
        let minutes = now.getMinutes().toString().padStart(2, '0');
        return {
            today: year + "年" + month + "月" + date + "日" + "　" + hours + ":" + minutes
        }
    }
</script>

{% endblock %}

customer/app/templates/layout.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- tailwind css cdn -->
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

    <!-- alpine.js -->
    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>

    <link rel="shortcut icon" href="{{ url_for('static', filename='img/fas_favicon.ico') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='images/apple-touch-icon180x180.png')}}">

    <title>ごみ袋 | furoshiki | fas |</title>
</head>
<body>
  {% block content %}
  {% endblock %}
  <script type="text/javascript" src="{{ url_for('static', filename='js/order.js') }}"></script>

</body>
</html>

customer/app/templates/login.html
<!doctype html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- alpine.js cdn -->
    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
    
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    
    <title>fas|ログイン</title>
</head>

<!-- ボディ -->
<body class="bg-gray-100 min-h-screen pt-10 pb-6 px-2 md:px-0" style="font-family:'Lato',sans-serif;">
{% from "_macros.html" import render_login_field_label, render_login_field, render_login_form_error %}

<!-- ヘッダー -->
<header class="max-w-sm mx-auto">
    <a href="#">
        <h1 class="object-center">
            <img class="object-contain h-16 w-full" src="../static/img/logo_FUROSHIKI.png" alt="furoshiki">
        </h1>
    </a>
</header>

<!-- display errors -->
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="max-w-sm mx-auto bg-red-100 border border-red-400 text-red-700 my-5 px-4 py-3 rounded" x-data="{ show: true }" x-show="show" x-init="setTimeout(() => show = false, 3000)">
            <div class="flex justify-center">
              <p class="text-sm">{{ message }}</p>
            </div>
        </div>
        {% endfor %}
    {% endif %}
{% endwith %}

<!-- メイン -->
<main class="bg-white max-w-sm mx-auto p-8 md:p-12 my-5 rounded-lg shadow-lg">
    <section>
        <h2 class="font-bold text-2xl text-gray-700">fas</h2>
        <p class="text-gray-600 pt-2">ログイン</p>
    </section>
    
    <section class="mt-5">
        <form class="flex flex-col" action="/login" method="POST" name="login_form">
            {{ form.csrf_token }}

            <div class="mb-6 pt-3">
                {{ render_login_field_label(form.email, 'メールアドレス') }}
                {{ render_login_field(form.email, class_="w-full text-gray-700 focus:outline-none
                focus:bg-gray-100 border-b border-gray-300 focus:border-blue-600 transition duration-500 px-3 pb-1") }}
            </div>

            <div class="mb-6 pt-3 rounded">
                {{ render_login_field_label(form.password, 'パスワード') }}
                {{ render_login_field(form.password, class_="w-full text-gray-700 focus:outline-none
                focus:bg-gray-100 border-b border-gray-300 focus:border-blue-600 transition duration-500 px-3 pb-1", autocomplete="on") }}
            </div>

            <button class="my-5 bg-blue-600 hover:bg-blue-800 text-white text-sm py-2 rounded shadow-lg
               hover:shadow-xl transition duration-200" type="submit">ログイン</button>
        </form>
    </section>
</main>

<!-- footer -->
<footer class="max-w-lg mx-auto flex justify-center text-gray-600 text-xs">
    <span class="mx-3">fas 3.0</span>
</footer>

</body>
</html>

customer/app/templates/navbar.html
<nav x-data="{ open: false }" class="bg-white sticky top-0 shadow-md px-3 py-3">
    <div class="max-w-4xl mx-auto">
        <div class="flex justify-between">
            <div class="flex space-x-5">
                <!-- logo -->
                <div>
                    <a href="/" class="flex items-center py-3">
                        <img src="{{ url_for('static', filename='img/logo_FUROSHIKI.png') }}" width=33 height=36
                        class="" alt="furoshiki logo">
                </div>

                <!-- primary nav -->
                <div class="hidden md:flex items-center space-x-1">
                    <a href="/" class="py-3 px-3 text-gray-700 hover:text-gray-900 hover:underline">ホーム</a>
                    {% if current_user.is_hq %}
                    <a href="/stats" class="py-3 px-3 text-gray-700 hover:text-gray-900 hover:underline">管理データ</a>
                    {% endif %}
                </div>
            </div>

            <!-- secondary nav -->
            <div class="hidden md:flex items-center space-x-5">
                <p>{{ current_user.email }}</p>
                <a href="/logout" class="text-blue-600 hover:underline hover:text-blue-800">ログアウト</a>
            </div>

            <!-- mobile button goes here -->
            <div class="md:hidden flex items-center">
                <button x-on:click="open = ! open">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" /></svg>
                </button>
            </div>
        </div>
    </div>

    <!-- mobile menu goes here -->
    <div x-bind:class="open ? '' : 'hidden'" class="md:hidden">
    <a href="/" class="block py-2 px-3 text-gray-700 hover:bg-gray-200">ホーム</a>
    {% if current_user.is_hq %}
    <a href="/stats" class="py-3 px-3 text-gray-700 hover:text-gray-900 hover:underline">管理データ</a>
    {% endif %}

    <div class="block py-2 px-3">
        {% if current_user.is_authenticated %}
        {{ current_user.email }}
        {% endif %}
    </div>
    <a href="/logout" class="block py-2 px-3 text-blue-600 hover:bg-gray-200">ログアウト</a>
    </div>
</nav>

customer/app/templates/order-detail.html
{% extends "layout.html" %}
{% block content %}
{% include "navbar.html" %}
{% include "_flashing.html" -%}

<div class="container max-w-4xl mx-auto md:w-1/3" x-data="{ open: false }">

    <div class="mx-3 my-10">
        <h1 class="my-5 font-bold text-lg">詳細</h1>

        <!-- order details go here-->
            <div class="w-full border p-6 rounded-lg shadow-lg">
                <div class="flex border-b items-end justify-between">
                    <h1 class="font-bold text-lg"><span class="text-sm font-normal text-gray-500">受注 ID</span> {{ '{:06d}'.format(order.id) }}</h1>
                    <p class="">{{ order.date.strftime('%Y-%m-%d %H:%M') }}</p>    
                </div>
                <p class="font-bold my-3">{{ order.shop.name }}</p>
                <p class="font-bold my-3">{{ order.shop.prefecture }}{{ order.shop.city }}{{ order.shop.town }}
                    {{ order.shop.address }}{{ order.shop.bldg }}
                </p>
                <p class="font-bold my-3"><span class="text-base font-normal text-gray-500">
                    {{ order.item }}
                </span> {{ order.product.name }}</p>
                <p class="font-bold my-3">{{ order.price }}
                    <span class="text-sm font-normal text-gray-500">円</span>
                </p>
                <p class="font-bold my-3">{{ order.qty }} <span class="text-sm font-normal text-gray-500">個</span></p>

            </div>

            <!-- order requests go here-->
            {% if order.item != 901 %}
            <div class="mt-3 w-full border p-6 rounded-lg shadow-lg">
                <h2 class="text-base font-bold border-b mb-3">配送に関する依頼</h2>
                {% if order.request %}
                <p class="text-sm text-gray-500">指定日<span class="ml-5 text-base text-gray-800 font-bold">{{ order.request.delivery_date or ''}}</span></p>
                <p class="mt-3 text-sm text-gray-500">時間帯
                    <span class="ml-5 text-base text-gray-800 font-bold">
                        {% if order.request.time_range == '1' %}
                        午前
                        {% elif order.request.time_range == '2' %}
                        午後
                        {% else %}
                        {% endif %}
                    </span>
                </p>
                <p class="mt-3 text-sm text-gray-500">依頼事項<span class="ml-5 text-sm text-gray-800 font-bold">{{ order.request.memo or ''}}</span></p>
                {% else %}
                <p>なし</p>
                {% endif %}
            </div>
            {% endif %}

            {% if order.shippings %}
            <div class="mt-3 w-full border p-6 rounded-lg shadow-lg">
                <h2 class="text-base font-bold border-b mb-3">出荷</h2>
                {% for shipping in order.shippings %}
                <ul class="mb-3">
                    <li><span class="text-xs text-gray-500">出荷日</span> {{ shipping.shipped_on }}</li>
                    <li><span class="text-xs text-gray-500">お問合せ番号</span> 
                        <a href="https://track.seino.co.jp/cgi-bin/gnpquery.pgm?GNPNO1={{ shipping.code }}" 
                        class="text-blue-500 text-lg hover:text-blue-700 hover:underline" target="_blank" rel="noopener">
                          {{ shipping.code }} &#x2197;
                        </a>
                    </li>
                </ul>
                {% endfor %}
            </div>
            {% endif %}
    </div>
</div>
{% endblock %}

customer/app/templates/stats.html
{% extends "layout.html" %}
{% block content %}
{% include "navbar.html" %}
{% include "_flashing.html" -%}

<div class="container md:max-w-md mx-auto">

    <div class="mt-6 flex justify-between px-3" x-data="getToday">
        <h1 class="mx-2 mt-8 text-xl font-bold text-gray-500">受注データ</h1>
        <p class="text-sm text-gray-500 self-end" x-text="today"></p>
    </div>

    <!-- date range select -->
    <div class="md:max-w-md md:mx-auto mx-2 mt-3 py-7 px-5 border rounded-lg shadow-lg">
        <h2 class="text-gray-500">範囲選択</h2>
        <form class="mt-7 mx-auto text-center" action="/stats" method="GET">
            <div class="text-sm">
                <label for="date_from" class="hidden">から</label>
                <input class="border-b" type="date" min="2020-09-01" name="date_from" id="date_from" required>
                <label for="date_to" class="px-3">〜</label>
                <input class="border-b" type="date" min="2020-09-01" name="date_to" id="date_to" required>    
            </div>
            <button type="submit" class="block w-full bg-blue-500 hover:bg-blue-800 text-sm text-white mt-7 py-1 px-5 rounded-full shadow-xl">
                検索
            </button>
        </form>
    </div>

    <!-- search results -->
    {% if date_from and date_to %}
    <div class="md:max-w-md md:mx-auto mx-2 mt-6 py-7 px-5 border rounded-lg shadow-lg">
        <div class="text-lg">
            <span class="text-sm text-gray-500 mr-5">対象期間</span>
            <span class="border-b">{{ date_from or '' }}</span>
            <span class="text-gray-500 text-sm">〜</span>
            <span class="border-b">{{ date_to or '' }}</span>
        </div>
        <div class="mt-3 text-sm text-gray-500">
            <span class="mr-5">CO<sub>2</sub> 削減量</span>
            <span class="text-3xl text-gray-800 border-b mr-1">{{ co2 | round(1,'floor') }}</span>
            t<span class="text-xs border-b">CO<sub>2</sub></span>
        </div>
        <div class="mt-3 text-sm text-gray-500">
            <span class="mr-5">再生材使用量</span>
            <span class="text-3xl text-gray-800 border-b mr-1">{{ pcr | round(1,'floor') }}</span>
            <span class="text-xs border-b">トン</span>
        </div>

    </div>
    {% endif %}
    <!--  -->
    <div class="md:max-w-md md:mx-auto my-5 mx-2">

    {% if orders %}

    <p class="text-blue-500 px-2">
    {% for page_num in orders.iter_pages(left_edge=3, right_edge=3) %}
        {% if page_num %}
            {% if orders.page == page_num %}
            <a href="{{ url_for('cs.stats', date_from=date_from, date_to=date_to, page=page_num) }}" class="underline">
                {{ page_num }}
            </a>
            {% else %}
            <a href="{{ url_for('cs.stats', date_from=date_from, date_to=date_to, page=page_num) }}" class="hover:text-blue-800">
                {{ page_num }}
            </a>
            {% endif %}
        {% endif %}
    {% endfor %}
    </p>
    
    <table class="table-auto w-full text-sm">
        <thead>
            <tr class="border-b border-black">
                <th clss="py-2">番号</th>
                <th class="py-2">受注日</th>
                <th class="py-2">事業所</th>
                <th class="py-2">商品</th>
                <th class="py-2">単価</th>
                <th class="py-2">数量</th>
            </tr>
        </thead>

        {% for order in orders.items %}
        <tbody>
            <tr class="border-b">
                <td>{{ '{:06d}'.format(order.id) }}</td>
                <td>{{ order.date.strftime('%m-%d') }}</td>
                <td>{{ order.customer_id }}-{{ order.shop_id }} {{ order.shop.name }}</td>
                <td>{{ order.product.abbre }}</td>
                <td class="text-right">{{ '{:,d}'.format(order.price) }}</td>
                <td class="text-right">{{ order.qty }}</td>
            </tr>
        </tbody> 
        {% endfor %}
    </table>
    {% endif %}
    </div>

</div>

<!-- alpine.js -->
<script>
    const getToday = () => {
        let now = new Date();
        let year = now.getFullYear();
        let month = now.getMonth() + 1;
        let date = now.getDate();
        let hours = now.getHours().toString().padStart(2, '0');
        let minutes = now.getMinutes().toString().padStart(2, '0');
        return {
            today: year + "年" + month + "月" + date + "日" + "　" + hours + ":" + minutes
        }
    }
</script>

{% endblock %}