sf/app/customer/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, StringField, SelectField
from wtforms.validators import InputRequired, NumberRange, Length, Regexp, DataRequired

from ..models import Staff

class CustomerRegisterForm(FlaskForm):
    id = IntegerField('取引先ID', validators=[InputRequired('IDは必須です。'),
                                           NumberRange(min=1, max=99999, message='IDは最大5桁です。')])
    name = StringField('取引先名', validators=[InputRequired('取引先名を入力して下さい。')])
    staff = SelectField('営業担当', validators=[InputRequired('営業担当者を入力してください。')])

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._set_staffs()

    def _set_staffs(self):
        staffs = Staff.query.filter(Staff.is_inactive==False).all()
        # set staffs from db as tuple(value, text)
        self.staff.choices = [('', '')]+[(staff.id, staff.last_name + staff.first_name) for staff in staffs]


class ShopForm(FlaskForm):
    id = IntegerField('事業所ID', validators=[InputRequired('事業所IDを入力して下さい。'),
                                           NumberRange(min=1, max=99999, message='IDは最大5桁です')])
    shop_number = StringField('顧客の事業所番号')
    name = StringField('事業所名', validators=[InputRequired()])
    department = StringField('部署/担当')
    zip = StringField('郵便番号', validators=[InputRequired('郵便番号を入力して下さい。'),
                                          Length(min=7, max=7, message='郵便番号は7桁です'),
                                          Regexp('[0-9]+', message='半角数字のみで7桁です')])
    prefecture = StringField('都道府県', validators=[InputRequired('都道府県を入力して下さい。')])
    city = StringField('市区町村', validators=[InputRequired('市区町村を入力して下さい。')])
    town = StringField('町域', validators=[InputRequired('町域を入力して下さい。')])
    address = StringField('番地', validators=[InputRequired('番地以下を入力して下さい。')])
    building = StringField('建物名他')
    telephone = StringField('電話番号', validators=[InputRequired('電話番号を入力して下さい。'),
                                                Regexp('[0-9]+-[0-9]+-[0-9]+', message='数字-数字-数字です。')])

sf/app/customer/views.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_required
from ..extentions import db
from ..models import Customer, Shop, ProductOrder, Product, CustomerContractPrice
from .forms import ShopForm, CustomerRegisterForm


customer = Blueprint('customer', __name__, url_prefix='/customer')

@customer.route('/')
@login_required
def index():
    
    if not request.args:
        return render_template('customer/customer.html')

    q = request.args.get('q')

    if q.isdigit():
        q = q
        result = Customer.query.get(q)

        if result:
            return redirect(url_for('customer.profile', id=q))
        else:
            return redirect(url_for('customer.index'))

    search = "%{}%".format(q)

    page = request.args.get('page', default=1, type=int)
    result = Customer.query.filter(Customer.name.like(search)).paginate(page=page, per_page=20)
    count = len(Customer.query.filter(Customer.name.like(search)).all())
    return render_template('customer/customer.html', customers=result, count=count, search=search)


# register customer
@customer.route('/register', methods=['GET', 'POST'])
@login_required
def register():

    form = CustomerRegisterForm()

    if form.validate_on_submit():
        id = request.form['id']
        name = request.form['name']
        staff = request.form['staff']
        register_items = request.form.get('registerItems')

        # check if requested id already exists in the db
        exists = Customer.query.get(id)
        
        if exists:
            return redirect(url_for('customer.profile', id=id))
        else:
            new_customer = Customer(id=id, name=name, staff=staff)
            db.session.add(new_customer)
            db.session.commit()

            if register_items:

                flash('新規取引先を登録しました。', 'success')

                return redirect(url_for('customer.register_contract_price', id=id))

            flash('新規取引先を登録しました。', 'success')

            return redirect(url_for('customer.profile', id=id))

    return render_template('customer/register.html', form=form)


# show and update customer profile
@customer.route('/<int:id>')
@customer.route('/<int:id>/<mode>', methods=['GET', 'POST'])
@login_required
def profile(id, mode=None):

    page = request.args.get('page', 1, type=int)
    customer = Customer.query.get_or_404(id)

    shops = Shop.query.filter_by(customer_id=id).paginate(page=page, per_page=20)

    items_prices = CustomerContractPrice.query.filter_by(customer_id=id).all() 
    registered_items = len(CustomerContractPrice.query.filter_by(customer_id=id).all())

    if mode == 'edit':

        form = CustomerRegisterForm(obj=customer)

        if form.validate_on_submit():
            customer.name = request.form['name']
            customer.staff = request.form['staff']
            db.session.commit()
            
            flash('取引先情報を更新しました。', 'success')

            return redirect(url_for('customer.profile', id=id))

        return render_template('customer/update.html', customer=customer, form=form)

    return render_template('customer/profile.html', customer=customer, shops=shops, items_prices=items_prices, registered_items=registered_items)


@customer.route('/shop/')
@login_required
def shop():

    q = request.args.get('q')

    if not q:
        return render_template('customer/customer.html')

    search = "%{}%".format(q)
    page = request.args.get('page', default=1, type=int)
    shops = Shop.query.filter(Shop.name.like(search)).paginate(page=page, per_page=20)
    count = len(Shop.query.filter(Shop.name.like(search)).all())

    return render_template('customer/customer.html', shops=shops, count=count, q=q)


# register shop
@customer.route('/<int:customer_id>/register', methods=['GET', 'POST'])
@login_required
def shop_register(customer_id):

    form = ShopForm()
    customer = Customer.query.get(customer_id)

    if form.validate_on_submit():

        id = request.form['id']

        # check if the shop already exists in the db
        exists = Shop.query.get((customer_id, id))

        if exists:
            return redirect(url_for('customer.shop_profile', customer_id=customer_id, id=id))

        new_shop = Shop()
        new_shop.customer_id = customer_id
        new_shop.id = request.form['id']
        new_shop.shop_number = request.form.get('shop_number')
        new_shop.name = request.form['name']
        new_shop.department = request.form.get('department')
        new_shop.zip = request.form['zip']
        new_shop.prefecture = request.form['prefecture']
        new_shop.city = request.form['city']
        new_shop.town = request.form['town']
        new_shop.address = request.form['address']
        new_shop.building = request.form.get('building')
        new_shop.telephone = request.form['telephone']

        db.session.add(new_shop)
        db.session.commit()

        flash('事業所を登録しました。', 'success')

        return redirect(url_for('customer.profile', id=customer_id))
    
    return render_template('customer/shop-register.html', form=form, customer=customer)


# show and update shop information
@customer.route('<int:customer_id>/<int:id>')
@customer.route('<int:customer_id>/<int:id>/<mode>', methods=['GET', 'POST'])
@login_required
def shop_profile(customer_id, id, mode=None):

    shop = Shop.query.get_or_404((customer_id, id))
    orders = ProductOrder.query.filter_by(customer_id=customer_id).filter_by(shop_id=id).order_by(ProductOrder.id.desc()).all()

    if mode == 'edit':
        form = ShopForm(obj=shop)

        if request.method == 'POST':
            shop.name = request.form['name']
            shop.shop_number = request.form.get('shop_number')
            shop.department = request.form.get('department')
            shop.zip = request.form['zip']
            shop.prefecture = request.form['prefecture']
            shop.city = request.form['city']
            shop.town = request.form['town']
            shop.address = request.form.get('address')
            shop.building = request.form.get('building')
            shop.telephone = request.form['telephone']

            db.session.commit()

            flash('事業所の情報を更新しました。', 'success')

            return redirect(url_for('customer.shop_profile', customer_id=customer_id, id=id))

        return render_template('customer/shop-update.html', shop=shop, form=form)

    return render_template('customer/shop-profile.html', shop=shop, orders=orders)


@customer.route('/<int:id>/register-contract-price', methods=['GET', 'POST'])
@login_required
def register_contract_price(id):

    customer = Customer.query.get(id)
    items = Product.query.all()

    if request.method == 'POST':
        item1 = request.form['item1']
        item2 = request.form.get('item2')
        item3 = request.form.get('item3')
        item4 = request.form.get('item4')
        item5 = request.form.get('item5')


        item_price = CustomerContractPrice(customer_id=id, product_id=item1, price=request.form['itemPrice1'])
        db.session.add(item_price)

        if item2:
            item_price = CustomerContractPrice(customer_id=id, product_id=item2, price=request.form['itemPrice2'])
            db.session.add(item_price)

        if item3:
            item_price = CustomerContractPrice(customer_id=id, product_id=item3, price=request.form['itemPrice3'])
            db.session.add(item_price)

        if item4:
            item_price = CustomerContractPrice(customer_id=id, product_id=item4, price=request.form['itemPrice4'])
            db.session.add(item_price)

        if item5:
            item_price = CustomerContractPrice(customer_id=id, product_id=item5, price=request.form['itemPrice5'])
            db.session.add(item_price)

        db.session.commit()

        flash('商品と単価を登録しました。', 'success')

        return redirect(url_for('customer.profile', id=id))

    return render_template('customer/register-contract-price.html', customer=customer, items=items)


@customer.route('/<int:id>/add-contract-price', methods=['GET', 'POST'])
@login_required
def add_contract_price(id):

    customer = Customer.query.get(id)
    registered_items = CustomerContractPrice.query.filter_by(customer_id=id).all()

    filter_list = []
    for registered_item in registered_items:
        filter_list.append(registered_item.product_id)

    items = Product.query.filter(Product.id.not_in(filter_list)).all()
    

    if request.method == 'POST':
        item2 = request.form.get('item2')
        item3 = request.form.get('item3')
        item4 = request.form.get('item4')
        item5 = request.form.get('item5')

        if item2:
            item_price = CustomerContractPrice(customer_id=id, product_id=item2, price=request.form['itemPrice2'])
            db.session.add(item_price)

        if item3:
            item_price = CustomerContractPrice(customer_id=id, product_id=item3, price=request.form['itemPrice3'])
            db.session.add(item_price)

        if item4:
            item_price = CustomerContractPrice(customer_id=id, product_id=item4, price=request.form['itemPrice4'])
            db.session.add(item_price)

        if item5:
            item_price = CustomerContractPrice(customer_id=id, product_id=item5, price=request.form['itemPrice5'])
            db.session.add(item_price)

        db.session.commit()

        flash('商品と単価を追加しました。', 'success')

        return redirect(url_for('customer.profile', id=id))

    return render_template('customer/add-contract-price.html', customer=customer, registered_items=registered_items, items=items)


@customer.route('/<int:customer_id>/edit-contract-price/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_contract_price(customer_id, id):

    customer = Customer.query.get(customer_id)
    items = Product.query.all()

    registered_item = CustomerContractPrice.query.get(id)

    if request.method == 'POST':
        new_price = int(request.form['price'])

sf/app/templates/customer/customer.html
{% extends "layout.html" -%}
{% block content -%}
{% include "nav.html" -%}

{% if request.path == '/customer/shop/' %}
<div class="container max-w-4xl mx-auto" x-data="{open: 2}">
{% else %}
<div class="container max-w-4xl mx-auto" x-data="{open: 1}">
{% endif %}
    <p class="md:max-w-md md:mx-auto mx-2 mt-8 text-xl font-bold text-gray-500">顧客</p>
    
    <div class="md:max-w-md md:mx-auto mx-2 my-5 p-5 border rounded-lg shadow-lg">
        
        <!-- tab items -->
        <ul class="flex cursor-pointer text-center text-gray-500">
            <li class="w-1/2 py-3 hover:bg-gray-100" @click="open = 1" :class="{'text-blue-700 border-b-2 border-blue-600': open === 1}">取引先</li>
            <li class="w-1/2 py-3 hover:bg-gray-100" @click="open = 2" :class="{'text-blue-700 border-b-2 border-blue-600': open === 2}">事業所（配送先）</li>
        </ul>

        <!-- target customer == 1 -->
        <div class="my-8" x-show="open === 1">
            <form action="/customer" method="GET">
                <div class="relative flex">
                    <input class="w-full border-b bg-white h-10 px-5 pr-16 focus:outline-none focus:shadow" type="search" name="q" placeholder="取引先名キーワード or ID">
                    <button type="submit" class="absolute right-0 top-0 mt-3 mr-4">
                        <svg class="text-gray-600 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px"
                            viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve"
                            width="512px" height="512px">
                            <path
                            d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
                        </svg>
                    </button>
                </div>
            </form>

            <div class="mt-5 bg-white text-sm">
                <a href="/customer/register" class="text-blue-600 hover:underline hover:text-blue-800 flex">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline-block" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    <span class="ml-3">新規取引先を登録</span>
                </a>
            </div>
        </div>

        <!-- target shop == 2 -->
        <div class="my-8" x-show="open === 2">
            <form action="/customer/shop" method="GET">
                <div class="flex relative">
                    <input class="w-full border-b bg-white h-10 px-5 pr-16 focus:outline-none focus:shadow" type="search" name="q" placeholder="事業所名キーワード">
                    <button type="submit" class="absolute right-0 top-0 mt-3 mr-4">
                        <svg class="text-gray-600 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px"
                            viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve"
                            width="512px" height="512px">
                            <path
                            d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
                        </svg>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <!-- customer == 1 -->
    <div class="max-w-md mx-auto px-3" x-show="open === 1">
    {% if customers %}
    <p class="text-2xl font-bold">{{ count }} <span class="text-gray-500 text-sm">件の取引先</span></p>
    <p class="my-3 text-blue-600">
    {% for page_num in customers.iter_pages(left_edge=3, right_edge=3) %}
        {% if page_num %}
        {% if customers.page == page_num %}
        <a class="underline" href="{{ url_for('customer.index', q=q, page=page_num) }}">{{ page_num }}</a>
        {% else %}
        <a class="" href="{{ url_for('customer.index', q=q, page=page_num) }}">
            {{ page_num }}</a>
        {% endif %}

        {% else %}
        ...
        {% endif %}
    {% endfor %}
    </p>

    <table class="table-auto w-full my-5">
        <thead>
        <tr class="border-black border-b">
            <th>取引先ID</th>
            <th>取引先名</th>
        </tr>
        </thead>

        {% for customer in customers.items %}
        <tr class="border-b">
            <td>{{ customer.id }}</td>
            <td><a class="text-blue-500 hover:text-blue-800" href="/customer/{{ customer.id }}">{{ customer.name }}</a></td>
        </tr>
        {% endfor %}
    </table>

    {% endif %}
    </div>

    <!-- shop == 2 -->
    <div class="mx-auto max-w-md px-3"  x-show="open === 2">
    {% if shops %}
    <p class="text-2xl font-bold">{{ count }} <span class="text-gray-500 text-sm">件の事業所が見つかりました。</span></p>

    <p class="my-3 text-blue-600">
        {% for page_num in shops.iter_pages(left_edge=3, right_edge=3) %}
            {% if page_num %}
            {% if shops.page == page_num %}
            <a class="underline" href="{{ url_for('customer.shop', q=q, page=page_num) }}">{{ page_num }}</a>
            {% else %}
            <a class="" href="{{ url_for('customer.shop', q=q, page=page_num) }}">
                {{ page_num }}</a>
            {% endif %}
    
            {% else %}
            ...
            {% endif %}
        {% endfor %}
    </p>
    <table class="table-auto w-full my-5">
        <thead>
        <tr class="border-black border-b">
            <th>顧客ID</th>
            <th>事業所ID</th>
            <th>事業所名</th>
        </tr>
        </thead>
        {% for shop in shops.items %}
        <tr class="border-b">
            <td>{{ shop.customer_id }}</td>
            <td>{{ shop.id }}</td>
            <td><a href="/customer/{{ shop.customer_id }}/{{ shop.id }}" class="text-blue-500 hover:text-blue-800">
                {{ shop.name }}</a></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
    </div>

</div>
{% endblock %}

sf/app/templates/customer/for_delete_shop.html
{% extends "layout.html" -%}
{% block content -%}
{% include "navbar.html" -%}

<div class="container max-w-5xl mx-auto">
    <div class="max-w-md mx-auto my-5 py-5" x-data="{open: 2}">

        <ul class="flex cursor-pointer text-center text-gray-500">
            <li class="w-1/2 py-3" @click="open = 1" :class="{'text-blue-700 border-b-2 border-blue-600': open === 1}">取引先</li>
            <li class="w-1/2 py-3" @click="open = 2" :class="{'text-blue-700 border-b-2 border-blue-600': open === 2}">事業所（配送先）</li>
        </ul>

            <div class="my-16 items-center justify-between" x-show="open === 1">
                <div class="justify-center items-center">
                    <form action="/customer" method="GET">
                        <div class="relative flex">
                            <input class="w-full border-b bg-white h-10 px-5 pr-16 focus:outline-none focus:shadow" type="search" name="q" placeholder="取引先名キーワード or ID">
                            <button type="submit" class="absolute right-0 top-0 mt-3 mr-4">
                                <svg class="text-gray-600 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
                                xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px"
                                viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve"
                                width="512px" height="512px">
                                <path
                                d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
                            </svg>
                        </button>
                    </div>
                    </form>
                </div>
                <!-- -->
                <div class="mt-5 bg-white text-sm">
                    <a href="/customer/register" class="text-blue-600 hover:underline hover:text-blue-800 flex">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline-block" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                          </svg>
                          <span class="ml-3">新規取引先を登録</span>
                        </a>
                    </div>

            </div>

            <div class="my-16" x-show="open === 2">
                <form action="/customer/shop" method="GET">
                    <div class="flex relative">
                        <input class="w-full border-b bg-white h-10 px-5 pr-16 focus:outline-none focus:shadow" type="search" name="q" placeholder="事業所名キーワード">
                        <button type="submit" class="absolute right-0 top-0 mt-3 mr-4">
                            <svg class="text-gray-600 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px"
                            viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve"
                            width="512px" height="512px">
                            <path
                            d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
                        </svg>
                    </button>
                </div>
            </form>
        </div>
    </div>

<!-- test -->

    {% if shops %}
    <div class="max-w-xl mx-auto">

    <p class="">{{ count }} 件の事業所が見つかりました。</p>

    <p class="my-3 text-blue-600">
    {% for page_num in shops.iter_pages(left_edge=3, right_edge=3) %}
        {% if page_num %}
        {% if shops.page == page_num %}
        <a class="underline" href="{{ url_for('customer.shop', q=q, page=page_num) }}">{{ page_num }}</a>
        {% else %}
        <a class="" href="{{ url_for('customer.shop', q=q, page=page_num) }}">
            {{ page_num }}</a>
        {% endif %}

        {% else %}
        ...
        {% endif %}
    {% endfor %}
    </p>

    <table class="table-auto w-full my-5">
        <thead>
        <tr class="border-black border-b">
            <th>顧客ID</th>
            <th>事業所ID</th>
            <th>事業所名</th>
            <th>住所</th>
            <th>TEL</th>
        </tr>
        </thead>

        {% for shop in shops.items %}
        <tr class="border-b">
            <td>{{ shop.customer_id }}</td>
            <td>{{ shop.id }}</td>
            <td><a href="/customer/{{ shop.customer_id }}/{{ shop.id }}" class="text-blue-500 hover:text-blue-800">
                {{ shop.name }}</a></td>
            <td>{{ shop.prefecture }}{{ shop.city }}{{ shop.town }}</td>
            <td>{{ shop.telephone }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
    {% endif %}

</div>
{% endblock %}

sf/app/templates/customer/shop-profile.html
{% extends "layout.html" %}
{% block content %}
{% include "nav.html" %}
{% include "_flashing.html" %}

<div class="container max-w-2xl mx-auto mt-5">
    <div class="max-w-lg mx-auto">

    <p class="font-bold text-xl text-gray-800">事業所情報</p>

    <div class="mx-auto p-6 bg-white shadow-lg rounded-lg my-10">
        <div class="flex justify-between items-center">
            <p class="text-gray-600">{{ shop.customer_id }} - {{ shop.id }}</p>
            <p class="text-blue-500 px-3 rounded-full hover:bg-blue-100">
                <a href="/customer/{{ shop.customer_id }}/{{ shop.id }}/edit">編集</a>
            </p>
        </div>
        <p class="mt-2 text-gray-600">{{ shop.customer.name }}</p>
        <h2 class="mt-2 text-gray-800 text-2xl">{{ shop.name }}</h2>
        <p class="mt-2 text-gray-600">{{ shop.shop_number or '' }}</p>
        <p class="mt-2 text-gray-600">{{ shop.department }}</p>
        <p class="mt-2 text-gray-600">{{ '〒{}-{}'.format(shop.zip[:3], shop.zip[3:]) }} {{ shop.prefecture }} {{ shop.city }}
            {{ shop.town }} {{ shop.address }} {{ shop.building or '' }}</p>
        <p class="mt-2 text-gray-600">{{ shop.telephone }}</p>
        <p class="mt-2 text-gray-500 text-sm text-right">{{ shop.registered_at.strftime('%Y-%m-%d %H:%M') if shop.registered_at else ''  }}</p>
    </div>
    </div>

    <div class="flex my-5 justify-center">
        <a href="/order/{{ shop.customer_id }}/{{ shop.id }}"
        class="bg-blue-500 text-white text-sm mx-5 py-2 px-7 rounded-full shadow-lg
        hover:bg-blue-800 transition duration-200">受注の入力へ</a>
    </div>

    <p class="font-bold text-lg my-5">受注履歴</p>

    <table class="table-auto my-5 w-full">
        <thead>
        <tr class="border-black border-b px-4 py-2">
            <th>受注ID</th>
            <th>受注日</th>
            <th>担当</th>
            <th>商品</th>
            <th>単価</th>
            <th>数量</th>
            </tr>
        </thead>
    {% for order in orders %}
        <tr class="border-b px-4 py-1">
            <td><a href="/order/{{ order.id }}" class="text-blue-500">
                    {{ '{:06d}'.format(order.id) }}</a></td>
            <td>{{ order.date.strftime('%Y-%m-%d') }}</td>
            <td>{{ order.staff.last_name }}</td>
            <td>{{ order.product.name }}</td>
            <td class="text-right">{{ order.price }}</td>
            <td class="text-right">{{ order.qty }}</td>
        </tr>
    {% endfor %}
    </table>
</div>

</div>

{% endblock %}

sf/app/templates/customer/update.html
{% extends "layout.html" %}
{% block content %}
{% from "_macros.html" import render_field_with_errors, render_select_field %}
{% include "nav.html" %}

<div class="max-w-6xl mx-auto">
    <div class="max-w-md mx-auto my-10">
        <p class="text-2xl">取引先の編集</p>
        <form method="POST">
        {{ form.csrf_token }}
        <div class="my-5">
            {{ render_field_with_errors(form.id, class_="w-full text-gray-800 border-b px-5 py-1
             focus:outline-none focus:bg-gray-100 focus:border-blue-500", readonly=True)}}
        </div>
        <div class="my-5">
            {{ render_field_with_errors(form.name, class_="w-full text-gray-800 border-b px-5 py-1
             focus:outline-none focus:bg-gray-100 focus:border-blue-500")}}
        </div>
        <div class="my-5">
            {{ render_select_field(form.staff, class_="w-full text-gray-800 px-3 pb-1 border-b border-gray-300 focus:outline-none
               focus:bg-gray-100 focus:border-blue-500 transition duration-500")}}
        </div>
        <p><a href="/customer/{{ customer.id }}" class="text-blue-500 hover:underline hover:text-blue-800">キャンセル</a>
            <button class="bg-blue-500 hover:bg-blue-800 text-white mx-7 py-1 px-7 rounded-full" type="submit">登録</button></p>
        </form>
    </div>
</div>

{% endblock %}