sf/app/downloads/views.py
from flask import Blueprint, render_template, request, redirect, url_for, make_response, session
from flask_login import login_required
from io import StringIO
from sqlalchemy import func

from ..models import ProductOrder
from .download import dl_general
from ..calcs import get_total_qty, get_total_amount, get_sum_by_item, get_sum_by_staff, get_orders

import datetime
import csv


downloads = Blueprint('downloads', __name__, url_prefix='/downloads')
JST = datetime.timezone(datetime.timedelta(hours=+9), 'JST')
now = datetime.datetime.now(JST)


@downloads.route('/')
@downloads.route('/<dl>')
@login_required
def index(dl=None):

    target_date = datetime.datetime.now(JST)

    total_qty = get_total_qty(target_date)
    total_amount = get_total_amount(target_date)
    sum_by_item = get_sum_by_item(target_date)
    sum_by_staff = get_sum_by_staff(target_date)

    if dl:
        orders = ProductOrder.query.filter(func.DATE(ProductOrder.date) == func.date(target_date)).all()

        file = StringIO()
        writer = csv.writer(file, lineterminator="\n")
        writer.writerow(
            ['注文番号', '登録日', '営業担当', '顧客ID', '事業所ID', '事業所名', '都道府県', '商品番号', '商品名', '単価', '数量']
            )

        for order in orders:
            writer.writerow([
                order.id, order.date, order.staff.last_name, order.customer_id, order.shop_id, order.shop.name, 
                order.shop.prefecture, order.item, order.product.name, order.price, order.qty
            ])

        response = make_response()
        response.data = file.getvalue().encode('sjis', 'replace')
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = 'attachment; filename=orders-' + target_date.strftime('%Y%m%d-%H%M') + '.csv'

        return response

    return render_template('downloads/index.html', target_date=target_date, total_qty=total_qty,
         total_amount=total_amount, sum_by_item=sum_by_item, sum_by_staff=sum_by_staff)


@downloads.route('/search')
@login_required
def search():

    target_date = request.args.get('targetDate')
    from_date = request.args.get('fromDate')
    to_date = request.args.get('toDate')
    layout = request.args.get('layout')

    total_qty = get_total_qty(target_date, from_date, to_date)
    total_amount = get_total_amount(target_date, from_date, to_date)
    sum_by_item = get_sum_by_item(target_date, from_date, to_date)
    sum_by_staff = get_sum_by_staff(target_date, from_date, to_date)

    orders = get_orders(target_date, from_date, to_date)

    if layout == 'general':

        file = StringIO()
        writer = csv.writer(file, lineterminator="\n")
        writer.writerow(
            ['注文番号', '登録日', '営業担当', '顧客ID', '事業所ID', '事業所名', '都道府県', '商品番号', '商品名', '単価', '数量']
            )

        for order in orders:
            writer.writerow([
                order.id, order.date, order.staff.last_name, order.customer_id, order.shop_id, order.shop.name, 
                order.shop.prefecture, order.item, order.product.name, order.price, order.qty
            ])

        response = make_response()
        response.data = file.getvalue().encode('sjis', 'replace')
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = 'attachment; filename=orders-' + target_date + '.csv'

        return response

    elif layout == 'accounting':

        file = StringIO()
        writer = csv.writer(file, lineterminator="\n")
        writer.writerow(
            ['注文番号', '登録日', '取引先', '事業所', '事業所名', '商品番号', '商品名', '単価', '数量', '出荷日', '出荷場所']
            )

        for order in orders:
            shipped_on = []
            shipped_by = []

            if order.shippings:
                # for date in order.shippings.shipped_on:
                #     shipped_on.append(date)

                # for shipper in order.shippings.registered_by:
                #     shipped_by.append(shipper)
                shipped_on = order.shippings.shipped_on
                shipped_by = order.shippings.registered_by

            else:
                pass
            
            writer.writerow([
                order.id, order.date, order.customer_id, order.shop_id, order.shop.name, 
                order.item, order.product.name, order.price, order.qty, shipped_on, shipped_by
            ])

        response = make_response()
        response.data = file.getvalue().encode('sjis', 'replace')
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = 'attachment; filename=orders-' + now.strftime('%Y-%m-%d') + '.csv'

        return response

    else:
        pass

    return render_template('downloads/searched.html', target_date=target_date, from_date=from_date, to_date=to_date,
         total_qty=total_qty, total_amount=total_amount, sum_by_item=sum_by_item, sum_by_staff=sum_by_staff)

sf/app/templates/downloads/index.html
{% extends "layout.html" %}
{% block content %}
{% include "nav.html" %}
<div class="container max-w-4xl mx-auto">
    <h1 class="md:max-w-md md:mx-auto mx-2 mt-8 text-xl font-bold text-gray-500">データのダウンロード</h1>

    <!-- date or dates range select -->
    <div x-data="{ open : 1 }" class="md:max-w-md md:mx-auto mx-2 mt-5 p-5 border rounded-lg shadow-lg">

        <ul class="flex cursor-pointer text-center text-gray-500">
            <li class="w-1/2 py-3" x-on:click="open = 1" :class="{'text-blue-700 border-b-2 border-blue-600': open === 1}">日付</li>
            <li class="w-1/2 py-3" x-on:click="open = 2" :class="{'text-blue-700 border-b-2 border-blue-600': open === 2}">範囲</li>
        </ul>

        <!-- date target == 1 -->
        <div class="mt-8" x-show="open === 1">
            <div class="my-5">
                <form action="/downloads/search" method="GET">
                    <div class="flex justify-center">
                        <input class="text-base text-center border-b-2 w-1/2" type="date" min="2020-09-01" name="targetDate" required>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="text-base text-white mt-8 py-1 px-5 rounded-full shadow-xl bg-blue-700 hover:bg-blue-500">
                            検索
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <!-- date range == 2-->
        <div class="mt-8" x-show="open === 2">
            <div class="my-5">
                <form action="/downloads/search" method="GET">
                    <div class="text-base text-center">
                        <label><span class="hidden">from</span>
                            <input class="border-b-2 text-center" type="date" min="2020-09-01" name="fromDate" id="fromDate" required>
                        </label>
                        <label for="toDate" class="px-3">〜
                            <input class="border-b-2 text-center" type="date" name="toDate" id="toDate" required>
                        </label>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="text-base text-white mt-8 py-1 px-5 rounded-full shadow-xl bg-blue-700 hover:bg-blue-500">
                            検索
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="md:max-w-md md:mx-auto mx-2 my-5 p-5 border rounded-lg shadow-lg">
        <div class="flex px-5">
            <p class="text-xl"><span class="text-sm text-gray-500">対象 </span>
                {% if target_date %}
                {{ target_date.strftime('%Y-%m-%d') }}
                {% elif from_date and to_date %}
                {{ from_date }}<span class="text-sm text-gray-500"> 〜 </span>{{ to_date }}
                {% else %}
                {% endif %}
            </p>
        </div>
        <div class="text-blue-700 my-5 p-5 border rounded-lg space-y-5">
            <div class="flex">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                </svg>
                <a href="/downloads/csv" class="text-sm hover:underline">
                    一覧のダウンロード
                </a>
            </div>
        </div>
        <div class="mb-5">
            <h2 class="font-bold">データ集計</h2>
        </div>

        <div class="text-center">
            <div class="flex justify-around">
                <p class="text-sm text-gray-500">売上<span class="text-xl text-gray-800"> {{ "{:,}".format(total_amount) if total_amount else 0 }}</span> 円</p>
                <p class="text-sm text-gray-500">箱数<span class="text-xl text-gray-800"> {{ "{:,}".format(total_qty) if total_qty else 0 }}</span> 箱</p>
            </div>

            {% if sum_by_item %}
            <div class="my-8 text-sm">
                <h3 class="text-left font-bold">商品別</h3>
                <ul class="px-5 my-3 text-gray-700">
                    <li class="flex border-b my-3 justify-between font-bold"><p class="w-3/5">商品</p><p class="w-1/5">数量</p><p class="w-fit">売上（円）</p></li>
                    {% for item in sum_by_item %}
                    <li class="flex border-b my-3 justify-between"><p class="w-3/5 text-left">{{ item[0] }} {{ item[1] }}</p><p class="w-1/5 text-center">{{ item[3] }}</p><p class="w-fit text-right">{{ "{:,}".format(item[4]) }}</p></li>
                    {% endfor %}
                </ul>    
            </div>
            {% endif %}
            {% if sum_by_staff %}
            <div class="my-8 text-sm">
                <h3 class="text-left font-bold">担当別</h3>
                <ul class="px-5 my-3 text-gray-700">
                    <li class="flex border-b my-3 justify-around font-bold"><p class="">担当</p><p class="">箱数</p><p class="">売上（円）</p></li>
                    {% for item in sum_by_staff %}
                    <li class="flex border-b my-3 justify-around"><p class="">{{ item[0] }} {{ item[1] }}{{ item[2] }}</p><p>{{ item[3] }}</p><p class="">{{ "{:,}".format(item[4]) }}</p></li>
                    {% endfor %}
                </ul>    
            </div>
            {% endif %}

        </div>

    </div>
</div>
{% endblock %}

{% block script %}
<script>
    const fromDate = document.querySelector("#fromDate");
    const toDate = document.querySelector('#toDate');

    fromDate.addEventListener("change", () => {

        toDate.min = fromDate.value;

        let min = fromDate.value.split("-");
        let minDate = new Date(min[0], min[1] - 1, min[2]);
        minDate.setDate(minDate.getDate() + 30)
        let maxDate = minDate.toLocaleDateString("ja-JP",{
            year : "numeric",
            month : "2-digit",
            day : "2-digit"
        }).split("/").join("-");

        toDate.max = maxDate;

    }, false);

</script>
{% endblock %}

sf/app/templates/downloads/searched.html
{% extends "layout.html" %}
{% block content %}
{% include "nav.html" %}
<div class="container max-w-4xl mx-auto">
    <h1 class="md:max-w-md md:mx-auto mx-2 mt-8 text-xl font-bold text-gray-500">データのダウンロード</h1>

    <!-- date or dates range select -->
    <div x-data="{ open : 1 }" class="md:max-w-md md:mx-auto mx-2 mt-5 p-5 border rounded-lg shadow-lg">

        <ul class="flex cursor-pointer text-center text-gray-500">
            <li class="w-1/2 py-3" x-on:click="open = 1" :class="{'text-blue-700 border-b-2 border-blue-600': open === 1}">日付</li>
            <li class="w-1/2 py-3" x-on:click="open = 2" :class="{'text-blue-700 border-b-2 border-blue-600': open === 2}">範囲</li>
        </ul>

        <!-- date target == 1 -->
        <div class="mt-8" x-show="open === 1">
            <div class="my-5">
                <form method="GET">
                    <div class="flex justify-center">
                        <input class="text-base text-center border-b-2 w-1/2" type="date" min="2020-09-01" name="targetDate" required>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="text-base text-white mt-8 py-1 px-5 rounded-full shadow-xl bg-blue-700 hover:bg-blue-500">
                            検索
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <!-- date range == 2-->
        <div class="mt-8" x-show="open === 2">
            <div class="my-5">
                <form method="GET">
                    <div class="text-base text-center">
                        <label><span class="hidden">from</span>
                            <input class="border-b-2 text-center" type="date" min="2020-09-01" name="fromDate" id="fromDate" required>
                        </label>
                        <label for="toDate" class="px-3">〜
                            <input class="border-b-2 text-center" type="date" name="toDate" id="toDate" required>
                        </label>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="text-base text-white mt-8 py-1 px-5 rounded-full shadow-xl bg-blue-700 hover:bg-blue-500">
                            検索
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="md:max-w-md md:mx-auto mx-2 my-5 p-5 border rounded-lg shadow-lg">
        <div class="flex px-5">
            <p class="text-xl"><span class="text-sm text-gray-500">対象 </span>
                {% if target_date %}
                {{ target_date }}
                {% elif from_date and to_date %}
                {{ from_date }}<span class="text-sm text-gray-500"> 〜 </span>{{ to_date }}
                {% else %}
                {% endif %}
            </p>
        </div>
        <div class="text-blue-700 my-5 p-5 border rounded-lg space-y-5">
            <div class="flex">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                </svg>
                <a href={{ url_for('downloads.search', targetDate=request.args.get('targetDate'), fromDate=request.args.get('fromDate'),
                toDate=request.args.get('toDate'), layout='general')}} class="text-sm hover:underline">
                    通常レイアウト
                </a>
            </div>
            <div class="flex">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                </svg>
                <a href={{ url_for('downloads.search', targetDate=request.args.get('targetDate'), fromDate=request.args.get('fromDate'),
                toDate=request.args.get('toDate'), layout='accounting') }} class="text-sm hover:underline">
                    山ちゃん用レイアウト
                </a>
            </div>

        </div>
        <div class="mb-5">
            <h2 class="font-bold">データ集計</h2>
        </div>

        <div class="text-center">
            <div class="flex justify-around">
                <p class="text-sm text-gray-500">売上<span class="text-xl text-gray-800"> {{ "{:,}".format(total_amount) if total_amount else 0 }}</span> 円</p>
                <p class="text-sm text-gray-500">箱数<span class="text-xl text-gray-800"> {{ "{:,}".format(total_qty) if total_qty else 0 }}</span> 箱</p>
            </div>

            {% if sum_by_item %}
            <div class="my-8 text-sm">
                <h3 class="text-left font-bold">商品別</h3>
                <ul class="px-5 my-3 text-gray-700">
                    <li class="flex border-b my-3 justify-between font-bold"><p class="w-3/5">商品</p><p class="w-1/5">数量</p><p class="w-fit">売上（円）</p></li>
                    {% for item in sum_by_item %}
                    <li class="flex border-b my-3 justify-between"><p class="w-3/5 text-left">{{ item[0] }} {{ item[1] }}</p><p class="w-1/5 text-center">{{ item[3] }}</p><p class="w-fit text-right">{{ "{:,}".format(item[4]) }}</p></li>
                    {% endfor %}
                </ul>    
            </div>
            {% endif %}
            {% if sum_by_staff %}
            <div class="my-8 text-sm">
                <h3 class="text-left font-bold">担当別</h3>
                <ul class="px-5 my-3 text-gray-700">
                    <li class="flex border-b my-3 justify-around font-bold"><p class="">担当</p><p class="">箱数</p><p class="">売上（円）</p></li>
                    {% for item in sum_by_staff %}
                    <li class="flex border-b my-3 justify-around"><p class="">{{ item[0] }} {{ item[1] }}{{ item[2] }}</p><p>{{ item[3] }}</p><p class="">{{ "{:,}".format(item[4]) }}</p></li>
                    {% endfor %}
                </ul>    
            </div>
            {% endif %}

        </div>

    </div>
</div>
{% endblock %}

{% block script %}
<script>
    const fromDate = document.querySelector("#fromDate");
    const toDate = document.querySelector('#toDate');

    fromDate.addEventListener("change", () => {

        toDate.min = fromDate.value;

        let min = fromDate.value.split("-");
        let minDate = new Date(min[0], min[1] - 1, min[2]);
        minDate.setDate(minDate.getDate() + 30)
        let maxDate = minDate.toLocaleDateString("ja-JP",{
            year : "numeric",
            month : "2-digit",
            day : "2-digit"
        }).split("/").join("-");

        toDate.max = maxDate;

    }, false);

</script>
{% endblock %}